/**: #Clean_Robot #KMS_241009
  ros__parameters:
    wheel_radius: 0.155       # 바퀴의 반경
    wheel_width: 0.1        # 휠 타이어의 측면 너비
    wheel_base: 0.955          # 앞바퀴 <-> 뒷바퀴 사이 거리  #241011
    wheel_tread: 0.72  #REAR        # 왼쪽 바퀴 중심과 오른쪽 바퀴 중심 사이
    front_overhang: 0.55       # 앞바퀴 중심과 차량 전면 사이
    rear_overhang: 0.54        # 뒷바퀴 중심과 차량 후면 사이
    left_overhang: 0.175      # 왼쪽 바퀴 중심과 차량 왼쪽 사이
    right_overhang: 0.175     # 오른쪽 바퀴 중심과 차량 오른쪽 사이
    vehicle_height: 1.58
    max_steer_angle: 0.523599 #30deg    # [rad] 
